### ISSUE TITLE
2 different skils, same thing 

### ISSUE THREAD

**Issue by LyndsaySolitude** [Decollates/MOD-POT-Nyctatyrannus#11]
The "tail" and the "right tail" are the same thing. Don't see a point in buying them if they are the same

**Comment by Decollates** [comment]
(Please fill out the form in its entirety when reporting issues.) 

Can you go into further details about this?

**Comment by LyndsaySolitude** [comment]
https://www.youtube.com/watch?v=dpDhpwhjoyI
Both these abilities are 100 coins but are the same attack.

**Comment by Decollates** [comment]
The video is private. Please change it to 'unlisted' so that it can be viewed in confidence.
