### ISSUE TITLE
[ISSUE] Very Bright 3 Call

### ISSUE THREAD

**Issue by Sharklordplays** [Decollates/MOD-POT-Nyctatyrannus#15]
```
Describe the bug
```
when on the default skin on pattern 3 with yellow bio then using your 3 call causes the red from the 3 call to become very bright
```
A clear and concise description of what the bug is.
```
the bloom effect from the 3 call with pattern 3 and yellow bio on the default skin causes a very bright red glow
```
To Reproduce
```
1. Go to 'character'
2. Click on 'default pattern 3'
3. Scroll down to 'yellow bio and 3 call'

```
Screenshots/Video/Gif
```
![PathOfTitans-Win64-Shipping Screenshot 2022 08 23 - 17 56 55 56](https://user-images.githubusercontent.com/111935113/186293935-bc0418d5-214e-47c3-8c9f-3537e2365342.png)

If applicable, add screenshots to help explain your problem. The more evidence describing the issue, the better.

**Comment by Nxzli** [comment]
The red glow when 3 calling is intentional!
