### ISSUE TITLE
Bite does not cancel calls [ISSUE] 

### ISSUE THREAD

**Issue by NeptuneNebula** [Decollates/MOD-POT-Nyctatyrannus#19]
```
Describe the bug
```
Biting while calling does not cancel the noise for the call, meaning the audio continues to play with no animation afterwards.

```
To Reproduce
```
1. Toggle a call, for best results the broadcast is best, using the vocal wheel or keybinds if available
2. Wait for call to begin clearly and audibly, then bite to cancel the animation
3. Audio continues to play despite the call animation being intercepted by the bite animation

```
Screenshots/Video/Gif
```
Video clip attached showing error/bug

https://user-images.githubusercontent.com/111959802/186369222-03cff93c-2976-42ac-8c0a-e082adc08adc.mp4

**Comment by Decollates** [comment]
Addressed in **Build 48bcffe-8.**
