### ISSUE TITLE
Lengthen time on the charged bite

### ISSUE THREAD

**Issue by NeptuneNebula** [Decollates/MOD-POT-Nyctatyrannus#21]
```
Have you checked to see if this suggestion has already been made?
```
Yes

```
What is your suggestion about?
```
Extend the time on the charged venom bite so it lasts longer.

```
Describe the cause for your suggestion?
```
Charged bites on other dinosaurs last slightly longer than the one for the Nycta, making it have an easier and more fair chance when having to charge up their bite for an ambush attack.

```
Additional context
```
Clip provided to show length and duration of attack, and if it can be extended to match other PoT dinosaurs with longer charges/wind ups.

https://user-images.githubusercontent.com/111959802/186376116-8602a984-4498-462e-be4d-2cc5c901eefb.mp4

**Comment by Decollates** [comment]
Declining suggestion - not necessary to adjust.
