### ISSUE TITLE
[ISSUE] Spectate not functioning with the mod on

### ISSUE THREAD

**Issue by FallenLord1** [Decollates/MOD-POT-Nyctatyrannus#22]
```
Bug description
```
Having the mod on makes attempting to go to spectate through the admin panel to be permanently freeze your game, turning the mod off upon ending task via task manager.

```
To Reproduce
```
1. Turn the mod on
2. Log into the game as any dinosaur
3. Go to the admin control panel and attempt to go to spectate

```
Screenshots/Video/Gif
```
https://www.youtube.com/watch?v=YQ3Xd7ZK7ZQ

**Comment by FallenLord1** [comment]
Issue does not seem to persist when going to spectate directly from character selection screen

**Comment by Nxzli** [comment]
This is a game bug, not a mod issue. The game developers will fix this.
