### ISSUE TITLE
[ISSUE] Nycta cannot collect bones for the quest

### ISSUE THREAD

**Issue by FallenLord1** [Decollates/MOD-POT-Nyctatyrannus#23]
```
Describe the bug
```
The "collect" action does not appear when approaching bones with a local bone collection quest

```
To Reproduce
```
1. Go to Corpse Cove
2. Receive bone collection quest
3. Try collecting bones

```
https://youtu.be/CvFzRJLR4pg
```

**Comment by Nxzli** [comment]
This is a game bug, not a mod bug. Will be fixed by the devs.
