### ISSUE TITLE
[ISSUE] Bioluminescence stays lit when attacking during call

### ISSUE THREAD

**Issue by MizuSky** [Decollates/MOD-POT-Nyctatyrannus#24]
**Describe the bug**

When utilising the emote wheel for aggressive and nycta love call that lightens the bioluminescence, should you interrupt the call via biting you will be stuck with a permanently lit bioluminescence for the respect emote.

Bright red for aggression call, and bright white that's interupted during the nycta love rainbow effect

**To Reproduce**
Bite while in the middle of a call that lights up the bioluminescence

1. Go to the emote wheel.
2. Click on either aggressive call or nycta heart emote call.
3. Bite during active call.
4. See you light up the world in all your gracious beauty that never fades until another call is made.

**Screenshots/Video/Gif**
https://www.youtube.com/watch?v=G8JA3V478mg

**Comment by Decollates** [comment]
Addressed in **Build 48bcffe-8**.

**Comment by SensualNighthawk** [comment]
I just found this bug again, and it's about 5 minutes since I discovered it.. I'm still glowing
