### ISSUE TITLE
[ISSUE] Bite sound not matching with animation

### ISSUE THREAD

**Issue by Nxzli** [Decollates/MOD-POT-Nyctatyrannus#3]
```
Describe the bug
```
When the Nyctatyrannus bites, the sound of the snap doesn't match up with the animation for it.

```
To Reproduce
```
1. Bite
2. Listen

```
Screenshots/Video/Gif
```
https://drive.google.com/file/d/1m3z_dkjAF4TzysDGj3See1woQsCOnQA7/view?usp=sharing

**Comment by Decollates** [comment]
Verified issue. Will be addressed in future patch.
