### ISSUE TITLE
[ISSUE] Buff call doesn't match animation

### ISSUE THREAD

**Issue by Nxzli** [Decollates/MOD-POT-Nyctatyrannus#4]
```
Describe the bug
```
The buff call sound doesn't match the animation.

```
To Reproduce
```
1. Use the buff call
2. Watch and listen

```
Screenshots/Video/Gif
```
https://drive.google.com/file/d/1Brghr7ZvIxBnAejMDt7NkSQt9eovuxa4/view?usp=sharing

**Comment by Decollates** [comment]
Verified. Will be addressed in future update.
