### ISSUE TITLE
[ISSUE] Eating

### ISSUE THREAD

**Issue by Warriornycta** [Decollates/MOD-POT-Nyctatyrannus#8]
```
Describe the bug
```
Food not filling up

```
To Reproduce
```
1. Go to a burrow
2. Dig up a critter and kill it
3. Eat critter

```
Screenshots/Video/Gif
```
https://streamable.com/qow4tq

**Comment by Decollates** [comment]
Issue verified. Likely a stat or singleplayer thing.

**Comment by FallenLord1** [comment]
> Issue verified. Likely a stat or singleplayer thing.

Have tested it a little bit, Nycta can only not replenish food directly from the food sources, it can still eat by picking up objects and swallowing them. 

https://youtu.be/CvFzRJLR4pg
